name: NetOperations-base

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install package
        run: |
          pip install poetry
          make install
      - name: Code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: d1ffa0ff630586d9dacc6abdda8e08d5af2334e9158b2271d6710f80b269c1ca
        with:
          coverageCommand: make test-coverage
          debug: True

